import type { WorldAssetManifest } from '../types/WorldAssetManifest';

export const IRONVALE_ASSET_MANIFEST: WorldAssetManifest = {
  zoneId: 'ironvale_outskirts',
  version: '0.2.0',
  meshes: [
    {
      id: 'mesh_pine_tree_01',
      path: 'meshes/foliage/pine_tree_01.glb',
      type: 'mesh_glb',
      sizeMB: 1.2,
      required: true,
      lodLevel: 0,
    },
    {
      id: 'mesh_pine_tree_01_lod1',
      path: 'meshes/foliage/pine_tree_01_lod1.glb',
      type: 'mesh_glb',
      sizeMB: 0.4,
      required: false,
      lodLevel: 1,
    },
    {
      id: 'mesh_pine_tree_01_lod2',
      path: 'meshes/foliage/pine_tree_01_lod2.glb',
      type: 'mesh_glb',
      sizeMB: 0.1,
      required: false,
      lodLevel: 2,
    },
    {
      id: 'mesh_dead_tree_01',
      path: 'meshes/foliage/dead_tree_01.glb',
      type: 'mesh_glb',
      sizeMB: 0.8,
      required: true,
      lodLevel: 0,
    },
    {
      id: 'mesh_bush_01',
      path: 'meshes/foliage/bush_01.glb',
      type: 'mesh_glb',
      sizeMB: 0.3,
      required: true,
      lodLevel: 0,
    },
    {
      id: 'mesh_grass_tall_patch',
      path: 'meshes/foliage/grass_tall_patch.glb',
      type: 'mesh_glb',
      sizeMB: 0.15,
      required: true,
      lodLevel: 0,
    },
    {
      id: 'mesh_boulder_large_01',
      path: 'meshes/rocks/boulder_large_01.glb',
      type: 'mesh_glb',
      sizeMB: 1.0,
      required: true,
      lodLevel: 0,
    },
    {
      id: 'mesh_boulder_medium_01',
      path: 'meshes/rocks/boulder_medium_01.glb',
      type: 'mesh_glb',
      sizeMB: 0.6,
      required: true,
      lodLevel: 0,
    },
    {
      id: 'mesh_cliff_face_01',
      path: 'meshes/rocks/cliff_face_01.glb',
      type: 'mesh_glb',
      sizeMB: 2.5,
      required: true,
      lodLevel: 0,
    },
    {
      id: 'mesh_stone_cluster_01',
      path: 'meshes/rocks/stone_cluster_01.glb',
      type: 'mesh_glb',
      sizeMB: 0.45,
      required: true,
      lodLevel: 0,
    },
    {
      id: 'mesh_dracor_shrine',
      path: 'meshes/landmarks/dracor_shrine.glb',
      type: 'mesh_glb',
      sizeMB: 2.0,
      required: true,
      lodLevel: 0,
    },
    {
      id: 'mesh_ruined_gate',
      path: 'meshes/landmarks/ruined_gate.glb',
      type: 'mesh_glb',
      sizeMB: 1.8,
      required: true,
      lodLevel: 0,
    },
    {
      id: 'mesh_old_bridge',
      path: 'meshes/landmarks/old_bridge.glb',
      type: 'mesh_glb',
      sizeMB: 1.5,
      required: true,
      lodLevel: 0,
    },
    {
      id: 'mesh_cobblestone_road',
      path: 'meshes/terrain/cobblestone_road.glb',
      type: 'mesh_glb',
      sizeMB: 0.8,
      required: true,
      lodLevel: 0,
    },
  ],
  textures: [
    {
      id: 'tex_terrain_ground_albedo',
      path: 'textures/terrain/ground_albedo.ktx2',
      type: 'texture_ktx2',
      sizeMB: 4.0,
      required: true,
    },
    {
      id: 'tex_terrain_ground_normal',
      path: 'textures/terrain/ground_normal.ktx2',
      type: 'texture_ktx2',
      sizeMB: 4.0,
      required: true,
    },
    {
      id: 'tex_terrain_ground_roughness',
      path: 'textures/terrain/ground_roughness.ktx2',
      type: 'texture_ktx2',
      sizeMB: 2.0,
      required: true,
    },
    {
      id: 'tex_pine_bark_albedo',
      path: 'textures/foliage/pine_bark_albedo.ktx2',
      type: 'texture_ktx2',
      sizeMB: 1.5,
      required: true,
    },
    {
      id: 'tex_pine_bark_normal',
      path: 'textures/foliage/pine_bark_normal.ktx2',
      type: 'texture_ktx2',
      sizeMB: 1.5,
      required: true,
    },
    {
      id: 'tex_pine_leaves_albedo',
      path: 'textures/foliage/pine_leaves_albedo.ktx2',
      type: 'texture_ktx2',
      sizeMB: 1.0,
      required: true,
    },
    {
      id: 'tex_rock_albedo',
      path: 'textures/rocks/rock_albedo.ktx2',
      type: 'texture_ktx2',
      sizeMB: 2.0,
      required: true,
    },
    {
      id: 'tex_rock_normal',
      path: 'textures/rocks/rock_normal.ktx2',
      type: 'texture_ktx2',
      sizeMB: 2.0,
      required: true,
    },
    {
      id: 'tex_cobblestone_albedo',
      path: 'textures/roads/cobblestone_albedo.ktx2',
      type: 'texture_ktx2',
      sizeMB: 1.5,
      required: true,
    },
    {
      id: 'tex_cobblestone_normal',
      path: 'textures/roads/cobblestone_normal.ktx2',
      type: 'texture_ktx2',
      sizeMB: 1.5,
      required: true,
    },
    {
      id: 'tex_shrine_emissive',
      path: 'textures/landmarks/shrine_emissive.ktx2',
      type: 'texture_ktx2',
      sizeMB: 0.5,
      required: true,
    },
    {
      id: 'tex_grass_tall_albedo',
      path: 'textures/foliage/grass_tall_albedo.ktx2',
      type: 'texture_ktx2',
      sizeMB: 0.8,
      required: true,
    },
    {
      id: 'tex_dead_tree_bark_albedo',
      path: 'textures/foliage/dead_tree_bark_albedo.ktx2',
      type: 'texture_ktx2',
      sizeMB: 1.0,
      required: true,
    },
    {
      id: 'tex_water_normal',
      path: 'textures/water/water_normal.ktx2',
      type: 'texture_ktx2',
      sizeMB: 0.5,
      required: false,
    },
  ],
  audio: [
    {
      id: 'audio_wind_pine',
      path: 'audio/ambient/wind_pine.ogg',
      type: 'audio_ogg',
      sizeMB: 2.5,
      required: true,
    },
    {
      id: 'audio_distant_wolves',
      path: 'audio/ambient/distant_wolves.ogg',
      type: 'audio_ogg',
      sizeMB: 1.8,
      required: true,
    },
    {
      id: 'audio_crackling_ember',
      path: 'audio/ambient/crackling_ember.ogg',
      type: 'audio_ogg',
      sizeMB: 1.2,
      required: true,
    },
    {
      id: 'audio_stream_flow',
      path: 'audio/ambient/stream_flow.ogg',
      type: 'audio_ogg',
      sizeMB: 2.0,
      required: false,
    },
    {
      id: 'audio_shrine_pulse',
      path: 'audio/events/shrine_pulse.ogg',
      type: 'audio_ogg',
      sizeMB: 0.8,
      required: false,
    },
    {
      id: 'audio_footsteps_cobblestone',
      path: 'audio/player/footsteps_cobblestone.ogg',
      type: 'audio_ogg',
      sizeMB: 0.5,
      required: true,
    },
  ],
};
