import type { Item } from '@dracor/shared';

export const STARTER_ITEMS: Item[] = [
  {
    id: 'item_ember_dagger',
    slug: 'ember_dagger',
    name: 'Dracor Ember Dagger',
    description: 'A curved obsidian-black dagger with a cracked volcanic edge glowing faint ember-orange.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 2,
    damageMax: 4,
    sellPrice: 5,
    metadata: { weaponClass: 'dagger' },
  },
  {
    id: 'item_long_sword',
    slug: 'long_sword',
    name: 'Dracor Long Sword',
    description: 'A blackened steel long sword with a glowing ember-orange rune channel through the fuller.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 4,
    damageMax: 7,
    sellPrice: 5,
    metadata: { weaponClass: 'longsword' },
  },
  {
    id: 'item_arming_sword',
    slug: 'arming_sword',
    name: 'Dracor Arming Sword',
    description: 'A battle-worn one-handed sword with bronze dragon-scale inlay near the base.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 3,
    damageMax: 6,
    sellPrice: 5,
    metadata: { weaponClass: 'arming_sword' },
  },
  {
    id: 'item_greatsword',
    slug: 'greatsword',
    name: 'Dracor Greatsword',
    description: 'A massive two-handed blade with a contained ember core glowing through the fuller.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 6,
    damageMax: 10,
    sellPrice: 5,
    metadata: { weaponClass: 'greatsword' },
  },
  {
    id: 'item_recurve_bow',
    slug: 'recurve_bow',
    name: 'Dracor Recurve Bow',
    description: 'An aggressive recurved bow of dark ashwood and black horn with dragon-horn tips.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 3,
    damageMax: 7,
    sellPrice: 5,
    metadata: { weaponClass: 'bow' },
  },
  {
    id: 'item_arrow_set',
    slug: 'arrow_set',
    name: 'Dracor Arrow Set',
    description: 'Handcrafted arrows with black steel dragon-tooth tips and ember-tipped raven fletching.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 2,
    damageMax: 5,
    sellPrice: 5,
    metadata: { weaponClass: 'arrows' },
  },
  {
    id: 'item_war_axe',
    slug: 'war_axe',
    name: 'Dracor War Axe',
    description: 'A compact blackened crescent axe with bronze dragonbone inlay and ember glow.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 4,
    damageMax: 8,
    sellPrice: 5,
    metadata: { weaponClass: 'axe' },
  },
  {
    id: 'item_war_hammer',
    slug: 'war_hammer',
    name: 'Dracor War Hammer',
    description: 'A heavy granite-like hammer with glowing white-gold cracks through the head.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 5,
    damageMax: 9,
    sellPrice: 5,
    metadata: { weaponClass: 'hammer' },
  },
  {
    id: 'item_spear',
    slug: 'spear',
    name: 'Dracor Spear',
    description: 'A dark ashwood spear with a blackened leaf-shaped blade and bronze dragon-wing socket.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 3,
    damageMax: 6,
    sellPrice: 5,
    metadata: { weaponClass: 'spear' },
  },
  {
    id: 'item_emberwood_staff',
    slug: 'emberwood_staff',
    name: 'Dracor Emberwood Staff',
    description: 'A twisted dark emberwood staff with a floating cracked ember crystal at the crown.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 4,
    damageMax: 5,
    sellPrice: 5,
    metadata: { weaponClass: 'staff' },
  },
  {
    id: 'item_ironroot_herb',
    slug: 'ironroot_herb',
    name: 'Ironroot Herb',
    description:
      'A tough, fibrous herb with medicinal properties. Grows in shaded forest groves.',
    itemType: 'material',
    rarity: 'common',
    requiredLevel: 1,
    sellPrice: 2,
    metadata: {},
  },
  {
    id: 'item_ashroot_toolbox',
    slug: 'ashroot_toolbox',
    name: 'Ashroot Toolbox',
    description:
      'A heavy iron toolbox containing precision smithing instruments. Property of Orin Ash.',
    itemType: 'quest',
    rarity: 'common',
    requiredLevel: 1,
    sellPrice: 0,
    metadata: { questItem: true },
  },
  {
    id: 'item_wolf_fang',
    slug: 'wolf_fang',
    name: 'Wolf Fang',
    description:
      'A sharp canine tooth from a Road Wolf. Valued by crafters and alchemists.',
    itemType: 'material',
    rarity: 'common',
    requiredLevel: 1,
    sellPrice: 3,
    metadata: {},
  },
  {
    id: 'item_simple_health_draught',
    slug: 'simple_health_draught',
    name: 'Simple Health Draught',
    description:
      'A basic healing potion brewed from Ironroot and clean water. Restores a small amount of health.',
    itemType: 'consumable',
    rarity: 'common',
    requiredLevel: 1,
    sellPrice: 5,
    metadata: { healAmount: 25 },
  },
];
