import type { Race } from '@dracor/shared';

export const RACES: Race[] = [
  {
    id: 'dracor',
    name: 'Dracor',
    tagline: 'Children of the Last Breath',
    description:
      'Born from the last breath of dying dragons, the Dracor carry fragments of ancient draconic power in their blood. They walk as mortals but bear the unmistakable marks of their lineage.',
    lore: 'When the great dragons fell in the Sundering War, their death-breath crystallized into seeds of power that took root in mortal bloodlines. The Dracor are the inheritors of that legacy — neither fully dragon nor fully human, but something ancient and dangerous in between. Every Dracor walks the line between mortal will and ancient instinct.',
    role: 'striker',
    difficulty: 2,
    playstyle: 'Balanced combatant who excels in sustained fights. High Spirit gives strong Dragon Memory synergy. Pairs well with any weapon.',
    traits: [
      'Ember eyes that glow faintly in darkness',
      'Scale markings along arms, neck, and spine',
      'Horn ridges unique to each individual',
      'Faint heat shimmer when channeling power',
      'Spectral dragon claws appear during combat',
    ],
    baseStats: {
      strength: 8,
      agility: 7,
      vitality: 8,
      spirit: 9,
      focus: 8,
    },
    abilities: [
      {
        id: 'dragon_blood',
        name: 'Dragon Blood',
        description: 'Passively regenerate 2% HP per second when below 30% health. The ancient blood refuses to let you fall.',
        type: 'passive',
      },
      {
        id: 'breath_of_the_ancients',
        name: 'Breath of the Ancients',
        description: 'Unleash a cone of elemental energy matching your Dragon Memory. Deals 150% Spirit damage and applies a 3s debuff.',
        type: 'active',
        cooldown: 25,
      },
    ],
    appearance: {
      eyeColors: ['Ember Gold', 'Crimson Fire', 'Sapphire Frost', 'Emerald Venom', 'Violet Storm', 'Silver Ash'],
      skinTones: ['Warm Bronze', 'Ashen Grey', 'Deep Obsidian', 'Pale Ivory', 'Burnished Copper'],
      markings: ['Ember Veins', 'Frost Lattice', 'Storm Lines', 'Shadow Web', 'Void Cracks', 'None'],
      hairStyles: ['Swept Flames', 'Obsidian Fall', 'Storm Crest', 'Ash Drift', 'Braided Horns', 'Shaved'],
      uniqueFeature: 'Horn Style',
      uniqueFeatureOptions: ['Swept Back', 'Crown Ridges', 'Twin Spires', 'Broken Stag', 'Coiled Ram', 'Vestigial Nubs'],
    },
    modelConfig: {
      bodyType: 'medium',
      height: 1.85,
      primaryColor: '#8B4513',
      secondaryColor: '#FF6B00',
      emissiveColor: '#FF4500',
      particleEffect: 'ember_sparks',
    },
  },
  {
    id: 'ironborn',
    name: 'Ironborn',
    tagline: 'Forged in the Deep Furnace',
    description:
      'Descendants of the mountain clans who survived the Sundering by retreating deep underground. Generations of living beside volcanic forges have made them dense, powerful, and nearly unbreakable.',
    lore: 'When dragonfire rained from the sky, the mountain clans sealed themselves inside the Deepfurnace — a volcanic forge-city carved into living rock. Over centuries, the mineral-rich waters and geothermal heat reshaped them. Their bones grew dense as iron, their skin took on a metallic sheen, and their endurance became legendary. Now they emerge, blinking, into a world that moved on without them.',
    role: 'tank',
    difficulty: 1,
    playstyle: 'Frontline wall. Absorb everything, die last. Low agility means slow positioning — commit to a spot and hold it.',
    traits: [
      'Metallic sheen to skin that deflects glancing blows',
      'Eyes like molten iron — orange-white and piercing',
      'Stocky, immensely dense musculature',
      'Geometric tattoos that glow when struck',
      'Voice resonates with a subterranean bass',
    ],
    baseStats: {
      strength: 11,
      agility: 5,
      vitality: 12,
      spirit: 6,
      focus: 6,
    },
    abilities: [
      {
        id: 'living_iron',
        name: 'Living Iron',
        description: 'Take 15% reduced physical damage at all times. Your iron-dense body shrugs off lesser blows.',
        type: 'passive',
      },
      {
        id: 'seismic_slam',
        name: 'Seismic Slam',
        description: 'Slam the ground with both fists, dealing 200% Strength damage in an area and stunning enemies for 2s.',
        type: 'active',
        cooldown: 30,
      },
    ],
    appearance: {
      eyeColors: ['Molten Orange', 'Forge White', 'Iron Grey', 'Copper Green', 'Coal Red'],
      skinTones: ['Granite Grey', 'Iron Black', 'Copper Bronze', 'Slate Blue', 'Obsidian'],
      markings: ['Forge Runes', 'Hammer Scars', 'Vein Lines', 'Circuit Patterns', 'None'],
      hairStyles: ['Iron Mohawk', 'Braided Chains', 'Shaved Clean', 'Stone Dreads', 'Forge Crest'],
      uniqueFeature: 'Metal Inlays',
      uniqueFeatureOptions: ['Gold Brow Plates', 'Iron Jaw Guard', 'Copper Cheek Lines', 'Silver Temple Bands', 'Bronze Skull Cap', 'None'],
    },
    modelConfig: {
      bodyType: 'heavy',
      height: 1.55,
      primaryColor: '#4A4A4A',
      secondaryColor: '#C0C0C0',
      emissiveColor: '#FF8C00',
      particleEffect: 'forge_sparks',
    },
  },
  {
    id: 'sylvhari',
    name: 'Sylvhari',
    tagline: 'Whispers of the Verdant Wild',
    description:
      'Spirits of the ancient forest given mortal form. The Sylvhari are living conduits between the natural world and civilization — graceful, deadly, and deeply attuned to the pulse of living things.',
    lore: 'Before the Sundering, the great forests were tended by pure spirits — formless guardians of root and branch. When dragonfire scorched the world, these spirits wove themselves into physical bodies to survive, becoming the Sylvhari. They remember being wind through leaves, rain on bark, moonlight through canopy. That memory makes them otherworldly, beautiful, and sometimes terrifyingly alien in their perspective.',
    role: 'skirmisher',
    difficulty: 3,
    playstyle: 'Hit-and-fade assassin. Devastating burst damage with Thornstrike, then vanish with Nature\'s Veil. Fragile — positioning is survival.',
    traits: [
      'Luminescent patterns beneath translucent skin',
      'Hair that shifts color with the seasons',
      'Elongated ears that twitch toward sound',
      'Move without disturbing grass or leaves',
      'Faint floral scent that changes with mood',
    ],
    baseStats: {
      strength: 5,
      agility: 12,
      vitality: 6,
      spirit: 11,
      focus: 6,
    },
    abilities: [
      {
        id: 'natures_veil',
        name: "Nature's Veil",
        description: 'While standing still for 3s, become invisible. Moving or attacking breaks the veil.',
        type: 'passive',
      },
      {
        id: 'thornstrike',
        name: 'Thornstrike',
        description: 'Launch a volley of thorns that deal 120% Agility damage and reduce target movement speed by 40% for 4s.',
        type: 'active',
        cooldown: 18,
      },
    ],
    appearance: {
      eyeColors: ['Leaf Green', 'Moonlight Silver', 'Petal Pink', 'Dawn Gold', 'Deep Violet'],
      skinTones: ['Birch White', 'Moss Green', 'Twilight Blue', 'Autumn Gold', 'Petal Rose'],
      markings: ['Vine Tracery', 'Leaf Veins', 'Bioluminescent Dots', 'Bark Patterns', 'Bloom Marks', 'None'],
      hairStyles: ['Willow Flow', 'Thorn Crown', 'Moss Locks', 'Petal Cascade', 'Branch Antlers', 'Wind-swept'],
      uniqueFeature: 'Ear Shape',
      uniqueFeatureOptions: ['Long Swept', 'Leaf-tipped', 'Feathered', 'Curled Fern', 'Short Pointed', 'Petal-edged'],
    },
    modelConfig: {
      bodyType: 'lean',
      height: 1.95,
      primaryColor: '#2E8B57',
      secondaryColor: '#98FB98',
      emissiveColor: '#00FF7F',
      particleEffect: 'floating_leaves',
    },
  },
  {
    id: 'ashwalker',
    name: 'Ashwalker',
    tagline: 'Survivors of the Scorched Age',
    description:
      'The last pure humans of the frontier — hardened, adaptive, and relentlessly resourceful. What they lack in supernatural gifts, they make up for in sheer determination and versatility.',
    lore: 'When the dragons fell and the world burned, most humans died. Those who survived did so through cunning, cooperation, and an iron refusal to lie down. The Ashwalkers are their descendants — generations tempered by hardship into something harder than steel. They have no magic in their blood, no ancient gifts. What they have is each other, their wits, and an unbreakable will to endure.',
    role: 'support',
    difficulty: 1,
    playstyle: 'Versatile all-rounder. No weakness, no spike. Rally Cry makes groups stronger. Best pick for players who want to adapt to any situation.',
    traits: [
      'Weathered features that speak of hard roads',
      'Scarred hands that know every weapon',
      'Eyes that miss nothing — always scanning',
      'Adaptable physiology — recover faster from any condition',
      'Natural leaders who inspire those around them',
    ],
    baseStats: {
      strength: 8,
      agility: 8,
      vitality: 8,
      spirit: 8,
      focus: 8,
    },
    abilities: [
      {
        id: 'adaptable',
        name: 'Adaptable',
        description: 'Gain +10% to your highest stat in combat. Ashwalkers excel at whatever they focus on.',
        type: 'passive',
      },
      {
        id: 'rally_cry',
        name: 'Rally Cry',
        description: 'Shout a battle cry that grants +20% attack speed and +10% damage to all nearby allies for 8s.',
        type: 'active',
        cooldown: 45,
      },
    ],
    appearance: {
      eyeColors: ['Steel Grey', 'Warm Brown', 'Ice Blue', 'Forest Green', 'Amber'],
      skinTones: ['Fair', 'Olive', 'Tanned', 'Dark Brown', 'Weathered Bronze'],
      markings: ['Battle Scars', 'Tribal Paint', 'Brand Marks', 'Road Dust Lines', 'None'],
      hairStyles: ['Warrior Knot', 'Loose and Wild', 'Shaved Sides', 'Braided Back', 'Short Cropped', 'Hood-worn'],
      uniqueFeature: 'War Paint',
      uniqueFeatureOptions: ['Eye Stripe', 'Half-face', 'Forehead Runes', 'Jaw Lines', 'Full War Mask', 'None'],
    },
    modelConfig: {
      bodyType: 'medium',
      height: 1.78,
      primaryColor: '#8B7355',
      secondaryColor: '#D2B48C',
      emissiveColor: '#FFD700',
    },
  },
  {
    id: 'voidtouched',
    name: 'Voidtouched',
    tagline: 'Marked by the Space Between',
    description:
      'When the dragons died, their death-screams tore holes in reality. Some mortals were caught in those rifts and returned... changed. The Voidtouched exist partially in another dimension, giving them terrifying arcane power at a terrible cost.',
    lore: 'The Void is not evil — it is absence. The space between stars, the silence between heartbeats, the darkness behind closed eyes. Those touched by it did not choose it; they were simply unlucky enough to be standing where reality tore open. Now they flicker between worlds, their bodies partially translucent, their minds touching thoughts that no mortal was meant to think. Most go mad. Those who survive become something extraordinary.',
    role: 'caster',
    difficulty: 5,
    playstyle: 'Glass cannon mage. Void Rupture is devastating AoE but you are fragile. Requires perfect positioning and cooldown management.',
    traits: [
      'Partially translucent — organs faintly visible',
      'Shadow tendrils drift from extremities',
      'Eyes are solid black with points of starlight',
      'Voice echoes as if speaking from far away',
      'Temperature drops in their presence',
    ],
    baseStats: {
      strength: 5,
      agility: 7,
      vitality: 5,
      spirit: 11,
      focus: 12,
    },
    abilities: [
      {
        id: 'phase_shift',
        name: 'Phase Shift',
        description: 'Take 25% reduced magic damage. Your partially-dimensional body lets spells pass through you.',
        type: 'passive',
      },
      {
        id: 'void_rupture',
        name: 'Void Rupture',
        description: 'Tear open a rift at target location dealing 180% Focus damage over 4s to all enemies in the area. Pulls enemies toward center.',
        type: 'active',
        cooldown: 35,
      },
    ],
    appearance: {
      eyeColors: ['Void Black', 'Starfield', 'Nebula Purple', 'Cosmic Blue', 'Eclipse Gold'],
      skinTones: ['Translucent Pale', 'Shadow Grey', 'Void Purple', 'Midnight Blue', 'Spectral White'],
      markings: ['Rift Scars', 'Star Maps', 'Void Fractures', 'Dimensional Tears', 'Constellation Lines', 'None'],
      hairStyles: ['Floating Wisps', 'Void Tendrils', 'Shadow Fall', 'Crystallized', 'Phase-shifted', 'None'],
      uniqueFeature: 'Void Manifestation',
      uniqueFeatureOptions: ['Third Eye', 'Floating Fragments', 'Shadow Crown', 'Rift Halo', 'Dimensional Echo', 'Subtle Flicker'],
    },
    modelConfig: {
      bodyType: 'ethereal',
      height: 1.82,
      primaryColor: '#1a0033',
      secondaryColor: '#6B0080',
      emissiveColor: '#9B30FF',
      particleEffect: 'void_particles',
    },
  },
  {
    id: 'bloodfane',
    name: 'Bloodfane',
    tagline: 'Heirs of the Crimson Court',
    description:
      'An ancient elven bloodline that survived the Sundering by making a pact with the dying dragons, infusing their blood with draconic essence. Tall, elegant, and dangerously beautiful — the Bloodfane wield arcane power that comes at a price only they are willing to pay.',
    lore: 'Before the dragons fell, the Bloodfane were the Aeltharin — high elves of the Crimson Court, masters of blood magic and political intrigue. When the Sundering came, their queen offered their entire bloodline to a dying dragon in exchange for survival. The dragon accepted, and the Aeltharin were reborn as the Bloodfane — elves whose veins run with liquid fire. They are feared and distrusted, but none can deny their power.',
    role: 'caster',
    difficulty: 4,
    playstyle: 'Blood magic risk/reward. Sacrifice HP for massive spell damage, then lifesteal it back. High skill ceiling — misplay and you kill yourself.',
    traits: [
      'Elongated ears with crimson-tipped points',
      'Veins that glow faintly red beneath porcelain skin',
      'Pupils that dilate into vertical slits when channeling',
      'Unnaturally graceful movement, almost predatory',
      'A faint metallic scent, like warm copper',
    ],
    baseStats: {
      strength: 5,
      agility: 9,
      vitality: 6,
      spirit: 12,
      focus: 8,
    },
    abilities: [
      {
        id: 'blood_tithe',
        name: 'Blood Tithe',
        description: 'Sacrifice 10% of current HP to gain 25% increased spell damage for 10s. Pain is the price of power.',
        type: 'active',
        cooldown: 20,
      },
      {
        id: 'crimson_ward',
        name: 'Crimson Ward',
        description: 'Heal 3% of damage dealt as HP. The blood you spill returns to you.',
        type: 'passive',
      },
    ],
    appearance: {
      eyeColors: ['Crimson', 'Blood Gold', 'Pale Violet', 'Ember Red', 'Silver-Rose'],
      skinTones: ['Porcelain', 'Moonlit Ivory', 'Pale Gold', 'Ash White', 'Dusk Rose'],
      markings: ['Blood Runes', 'Vein Traces', 'Court Tattoos', 'Pact Scars', 'Arcane Sigils', 'None'],
      hairStyles: ['Silver Cascade', 'Blood-tipped White', 'Raven Black', 'Braided Crown', 'Swept Noble', 'Short Court'],
      uniqueFeature: 'Ear Adornment',
      uniqueFeatureOptions: ['Gold Ear Cuffs', 'Crimson Jewel Tips', 'Chain Links', 'Rune Piercings', 'Feathered', 'None'],
    },
    modelConfig: {
      bodyType: 'lean',
      height: 1.92,
      primaryColor: '#4a0000',
      secondaryColor: '#cc0000',
      emissiveColor: '#ff0033',
    },
  },
  {
    id: 'stoneguard',
    name: 'Stoneguard',
    tagline: 'Unbroken Since the First Age',
    description:
      'Stocky, indomitable, and ancient beyond reckoning. The Stoneguard are a dwarven people who have lived beneath the mountains since before the dragons even existed. They measure time in geological epochs and grudges in centuries.',
    lore: 'The Stoneguard claim they were carved from the bones of the world itself — and looking at them, it is hard to argue. They predate the dragons, predate the elves, predate every race that walks the surface. When the Sundering shattered the world above, the Stoneguard barely noticed. Their deepholm kingdoms endured, as they always have. Now some venture topside, drawn by curiosity or exile, carrying hammers older than most civilizations.',
    role: 'tank',
    difficulty: 2,
    playstyle: 'Immovable fortress. Highest vitality in the game. Stonewall makes you invincible for 4s. Slow but nearly unkillable.',
    traits: [
      'Dense musculature — twice the weight of a human their size',
      'Beards that grow from birth and are never cut (braided with ore)',
      'Stone-grey or iron-dark skin with crystalline flecks',
      'Night vision that turns eyes to pale silver in darkness',
      'A deep resonant voice that carries through stone',
    ],
    baseStats: {
      strength: 10,
      agility: 4,
      vitality: 14,
      spirit: 5,
      focus: 7,
    },
    abilities: [
      {
        id: 'stonewall',
        name: 'Stonewall',
        description: 'Become immovable for 4s, reducing all incoming damage by 50% but unable to move. You ARE the wall.',
        type: 'active',
        cooldown: 40,
      },
      {
        id: 'mountain_born',
        name: 'Mountain Born',
        description: 'Immune to knockback and stun effects shorter than 2s. Mountains do not flinch.',
        type: 'passive',
      },
    ],
    appearance: {
      eyeColors: ['Pale Silver', 'Amber Ore', 'Deep Coal', 'Crystal Blue', 'Granite Green'],
      skinTones: ['Iron Grey', 'Stone Brown', 'Granite Dark', 'Copper Weathered', 'Chalk White'],
      markings: ['Clan Runes', 'Forge Burns', 'Gem Inlays', 'Mining Scars', 'None'],
      hairStyles: ['Triple Braid', 'Loose Mane', 'War Crest', 'Shaved with Runes', 'Iron Bands', 'Ancestor Knots'],
      uniqueFeature: 'Beard Style',
      uniqueFeatureOptions: ['Grand Forked', 'Iron-banded', 'Gem-studded', 'Battle-short', 'Ancestor Braids', 'Beardless (exile mark)'],
    },
    modelConfig: {
      bodyType: 'heavy',
      height: 1.4,
      primaryColor: '#3d3d3d',
      secondaryColor: '#888888',
      emissiveColor: '#d4a017',
    },
  },
  {
    id: 'grukhar',
    name: 'Grukhar',
    tagline: 'Wrath of the Broken Steppe',
    description:
      'Massive, tusked warriors from the scorched grasslands east of the frontier. The Grukhar live for battle — not out of bloodlust, but because their culture teaches that glory in combat is the only path to the afterlife. Every scar is a prayer.',
    lore: 'The Grukhar once ruled a vast steppe empire, but the Sundering turned their homeland into a wasteland of ash and bone. Rather than despair, they took it as a sign from their war-god Gruk: the old world was weak and deserved its death. The strong would build a new one. Now they roam the frontier in war-bands, seeking worthy foes and honourable death. They are not mindless brutes — their battle-poetry is considered the finest oral tradition in the known world.',
    role: 'striker',
    difficulty: 3,
    playstyle: 'Berserker. Gets stronger as you take damage. War Cry breaks enemy defenses. Go in hard, finish fast, or die gloriously.',
    traits: [
      'Towering height with thick green-grey or brown skin',
      'Prominent lower tusks, often decorated with metal caps',
      'Ritual scarification covering face, arms, and chest',
      'A deep, guttural accent that commands attention',
      'Battle-rage that causes veins to bulge and eyes to redden',
    ],
    baseStats: {
      strength: 13,
      agility: 6,
      vitality: 10,
      spirit: 5,
      focus: 6,
    },
    abilities: [
      {
        id: 'blood_rage',
        name: 'Blood Rage',
        description: 'When below 40% HP, gain +30% attack damage and +15% attack speed. Pain feeds the fury.',
        type: 'passive',
      },
      {
        id: 'war_cry',
        name: 'War Cry',
        description: 'Let loose a terrifying shout that fears enemies within 8m for 3s and reduces their armor by 20% for 6s.',
        type: 'active',
        cooldown: 35,
      },
    ],
    appearance: {
      eyeColors: ['Blood Red', 'Amber', 'War Gold', 'Pale Yellow', 'Charcoal'],
      skinTones: ['Moss Green', 'Steppe Brown', 'Ash Grey', 'Tundra Olive', 'War-painted Red'],
      markings: ['Battle Scars', 'Ritual Brands', 'Kill Tallies', 'Clan Glyphs', 'War Paint', 'None'],
      hairStyles: ['Topknot', 'Shaved War-stripe', 'Bone Braids', 'Loose Mane', 'Mohawk', 'None'],
      uniqueFeature: 'Tusk Style',
      uniqueFeatureOptions: ['Iron-capped', 'Gold-banded', 'Carved with Runes', 'Broken (veteran)', 'Natural', 'Trophy-hung'],
    },
    modelConfig: {
      bodyType: 'heavy',
      height: 2.1,
      primaryColor: '#3d4a2a',
      secondaryColor: '#8b6914',
      emissiveColor: '#cc3300',
    },
  },
  {
    id: 'skrix',
    name: 'Skrix',
    tagline: 'Quick Hands, Quicker Minds',
    description:
      'Small, cunning, and impossibly fast. The Skrix are a goblin-kin people who survived the Sundering through sheer ingenuity and a complete absence of pride. Where others fight, the Skrix negotiate. Where others build walls, the Skrix build escape tunnels.',
    lore: 'Nobody knows where the Skrix came from — least of all the Skrix themselves, who consider the question irrelevant. "We are here now, yes? That is what matters." They appeared in the ruins after the Sundering like rats after a flood, scavenging, trading, and building improbable contraptions from scrap. They are distrusted by everyone and allied with whoever pays best. Their engineering borders on genius, their morality borders on absent, and their survival instinct is unmatched.',
    role: 'skirmisher',
    difficulty: 3,
    playstyle: 'Evasion trickster. Hardest to hit, dirtiest fighter. Blind enemies, dodge everything, pick pockets between stabs.',
    traits: [
      'Small and wiry, rarely taller than a child',
      'Large pointed ears that swivel toward sound',
      'Quick, darting eyes — yellow, green, or orange',
      'Fingers that move with unsettling dexterity',
      'A high-pitched, rapid way of speaking',
    ],
    baseStats: {
      strength: 4,
      agility: 14,
      vitality: 5,
      spirit: 6,
      focus: 11,
    },
    abilities: [
      {
        id: 'slippery',
        name: 'Slippery',
        description: 'Dodge chance increased by 15%. Hard to hit what you cannot catch.',
        type: 'passive',
      },
      {
        id: 'dirty_trick',
        name: 'Dirty Trick',
        description: 'Throw a handful of dust/flash powder that blinds enemies in a cone for 3s and deals 80% Focus damage. No rules in survival.',
        type: 'active',
        cooldown: 22,
      },
    ],
    appearance: {
      eyeColors: ['Toxic Yellow', 'Copper Orange', 'Sewer Green', 'Ember Red', 'Pale Grey'],
      skinTones: ['Moss Green', 'Sewer Grey', 'Rust Brown', 'Pale Olive', 'Mushroom Tan'],
      markings: ['Gear Tattoos', 'Burn Scars', 'Ink Scribbles', 'Trade Brands', 'None'],
      hairStyles: ['Wild Tuft', 'Singed Mohawk', 'Rat-tail', 'Goggles-flattened', 'Bald Patchy', 'Wiry Explosion'],
      uniqueFeature: 'Ear Accessories',
      uniqueFeatureOptions: ['Brass Rings', 'Stolen Earrings', 'Notched (fights)', 'Goggles on Head', 'Feather Tuft', 'None'],
    },
    modelConfig: {
      bodyType: 'lean',
      height: 1.2,
      primaryColor: '#4a5a2a',
      secondaryColor: '#998844',
      emissiveColor: '#88aa00',
    },
  },
];

export function getRaceById(id: string): Race | undefined {
  return RACES.find((r) => r.id === id);
}
