import type { Item } from '@dracor/shared';

export const STARTER_WEAPONS: Item[] = [
  {
    id: 'weapon_ember_dagger',
    slug: 'ember_dagger',
    name: 'Dracor Ember Dagger',
    description:
      'A curved obsidian-black dagger with a cracked volcanic edge glowing faint ember-orange. Its predatory shape echoes a dragon claw.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 2,
    damageMax: 4,
    sellPrice: 5,
    metadata: { weaponClass: 'dagger', attackSpeed: 1.5 },
  },
  {
    id: 'weapon_long_sword',
    slug: 'long_sword',
    name: 'Dracor Long Sword',
    description:
      'A blackened steel long sword with a glowing ember-orange rune channel through the fuller. The swept dragon-horn crossguard marks its noble origin.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 4,
    damageMax: 7,
    sellPrice: 5,
    metadata: { weaponClass: 'longsword', attackSpeed: 0.8 },
  },
  {
    id: 'weapon_arming_sword',
    slug: 'arming_sword',
    name: 'Dracor Arming Sword',
    description:
      'A battle-worn one-handed sword with bronze dragon-scale inlay near the base. Reliable, balanced, and carried by frontier Roadwardens.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 3,
    damageMax: 6,
    sellPrice: 5,
    metadata: { weaponClass: 'arming_sword', attackSpeed: 1.0 },
  },
  {
    id: 'weapon_greatsword',
    slug: 'greatsword',
    name: 'Dracor Greatsword',
    description:
      'A massive two-handed blade with a contained ember core glowing through the fuller. Chipped edges speak of countless battles.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 6,
    damageMax: 10,
    sellPrice: 5,
    metadata: { weaponClass: 'greatsword', attackSpeed: 0.55 },
  },
  {
    id: 'weapon_recurve_bow',
    slug: 'recurve_bow',
    name: 'Dracor Recurve Bow',
    description:
      'An aggressive recurved bow of dark ashwood and black horn, with limb tips shaped like swept dragon horns. The bowstring hums with faint warmth.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 3,
    damageMax: 7,
    sellPrice: 5,
    metadata: { weaponClass: 'bow', attackSpeed: 0.85 },
  },
  {
    id: 'weapon_arrow_set',
    slug: 'arrow_set',
    name: 'Dracor Arrow Set',
    description:
      'Handcrafted arrows with black steel dragon-tooth tips and raven fletching tipped in ember-orange. One special arrow bears a glowing rune.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 2,
    damageMax: 5,
    sellPrice: 5,
    metadata: { weaponClass: 'arrows', attackSpeed: 1.3 },
  },
  {
    id: 'weapon_war_axe',
    slug: 'war_axe',
    name: 'Dracor War Axe',
    description:
      'A compact blackened crescent axe with bronze dragonbone inlay. The blade shape subtly echoes a dragon jaw, and ember light seeps from its center.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 4,
    damageMax: 8,
    sellPrice: 5,
    metadata: { weaponClass: 'axe', attackSpeed: 0.75 },
  },
  {
    id: 'weapon_war_hammer',
    slug: 'war_hammer',
    name: 'Dracor War Hammer',
    description:
      'A heavy granite-like hammer with glowing white-gold cracks through the head. One side crushes, the other pierces with a dragon-horn spike.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 5,
    damageMax: 9,
    sellPrice: 5,
    metadata: { weaponClass: 'hammer', attackSpeed: 0.65 },
  },
  {
    id: 'weapon_spear',
    slug: 'spear',
    name: 'Dracor Spear',
    description:
      'A dark ashwood spear with a blackened leaf-shaped blade and bronze dragon-wing socket. Cloth strips in muted red hang below the head.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 3,
    damageMax: 6,
    sellPrice: 5,
    metadata: { weaponClass: 'spear', attackSpeed: 1.0 },
  },
  {
    id: 'weapon_emberwood_staff',
    slug: 'emberwood_staff',
    name: 'Dracor Emberwood Staff',
    description:
      'A twisted dark emberwood staff with faint red glowing grain. A cracked ember crystal floats in a bronze claw frame at the crown.',
    itemType: 'weapon',
    rarity: 'common',
    requiredLevel: 1,
    damageMin: 4,
    damageMax: 5,
    sellPrice: 5,
    metadata: { weaponClass: 'staff', attackSpeed: 1.2 },
  },
];
